server:
  port: 8080

spring:
  application:
    name: food-booking-backend

  mail:
    host: smtp.gmail.com
    port: 587
    username: hucauvn37@gmail.com
    password: ikslbmonnppsaqoe
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/food-booking-db
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ""

# log sql  query
  jpa:
      show-sql: true
      hibernate:
          ddl-auto: update

  flyway:
    enabled: true
    validate-on-migrate: true
    baseline-on-migrate: true
    baseline-version: 0

  web:
    resources:
      static-locations: file:Image/ 

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

# Cấu hình Cloudinary
cloudinary:
  cloud-name: dlutz1pvz
  api-key: 692696427816334
  api-secret: g6nQ6n95Qg-VgMV0mK2Y8bthJzc

logging:
  level:
    root: info
    org.springframework.security: DEBUG
  file:
    name: logs/server.log
