server:
  port: 8080

spring:
  application:
    name: food-booking-backend

  mail:
    host: smtp.gmail.com
    port: 587
    username: hucauvn37@gmail.com
    password: ikslbmonnppsaqoe
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/food-booking-db
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ""

  flyway:
    enabled: true
    validate-on-migrate: true
    baseline-on-migrate: true
    baseline-version: 0

  web:
    resources:
      static-locations: file:Image/ 

logging:
  level:
    root: info
    org.springframework.security: DEBUG
  file:
    name: logs/server.log
